unused_files = """
AMBIGSUI.RRF MRHIST.RRF MRXW_CHI.RRF MRXW_DUT.RRF MRXW_FRE.RRF MRXW_HEB.RRF MRXW_JPN.RRF 
MRXW_NOR.RRF MRXW_RUS.RRF MRXW_SWE.RRF MRAUI.RRF MRMAP.RRF MRXW_CZE.RRF MRXW_EST.RRF MRXW_GER.RRF
MRXW_HUN.RRF MRXW_KOR.RRF MRXW_POL.RRF MRXW_SCR.RRF MRXW_TUR.RRF MRCOC.RRF MRXW_BAQ.RRF 
MRXW_DAN.RRF MRXW_FIN.RRF MRXW_GRE.RRF MRXW_ITA.RRF MRXW_LAV.RRF MRXW_POR.RRF
MRXW_SPA.RRF"""

unused_files = unused_files.split()


